language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools-24.0.3
    - tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

script: ./gradlew assembleRelease
